### PR TITLE
Exercise

### PR DESCRIPTION
**Pull request by ellisthomas**
@mgteutsch

### CODE REVIEW

**Comment by alexsaber89** [comment]
@ellisthomas, nice job!  You nailed pretty much all details of the assignment.  The only problem I see is that when I run your project, your images appear to be broken .  Make sure you add your images to an img/ directory, ensure their file paths are accurate in your img tags, and include them in your repository.

**Comment by ellisthomas** [comment]
@alexsaber89 thank you i just went in and made sure that the img directory was fixed think i just may have missed a step on my final push to github. Just let me know if it looks good now and if I am ok to merge. Thanks again

**Comment by alexsaber89** [comment]
@ellisthomas, can you go ahead and push up the img/ directory?

**Comment by ellisthomas** [comment]
@alexsaber89 pushed up

**Comment by alexsaber89** [comment]
@ellisthomas looks good! :+1:

**Comment by ellisthomas** [comment]
@alexsaber89 thanks man appreciate your help

**Pull request merged**
